FROM ubuntu:14.04

RUN apt-get update && \
    apt-get install -y build-essential gdb wget curl iputils-ping net-tools

COPY syscall_test_linux.c /root/
COPY vuln_buffer_overflow.c /root/

WORKDIR /root

RUN gcc -o syscall_test syscall_test_linux.c
RUN gcc -fno-stack-protector -z execstack -o vuln_buffer_overflow vuln_buffer_overflow.c
CMD ["/bin/bash"]
